campaigns/urls.py
from django.urls import include, path
from . import views
from django.contrib.auth.decorators import login_required



app_name = 'campaigns'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('campaign', login_required(views.CampaignView.as_view()), name='campaign'),
    #path('results/', views.ResultsView.as_view(), name='results'),
    path('results/', views.results, name='results'),
]

fundrazr/urls.py
from django.contrib import admin
from django.urls import include, path
from . import settings
from django.contrib.staticfiles.urls import static 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('campaigns.urls', namespace='campaigns')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

campaigns/models.py
from django.db import models
import json


class Campaign(models.Model):
	campaignTitle = models.CharField('campaignTitle', max_length=500, blank=True)
	amountRaised = models.CharField('amountRaised', max_length=100, blank=True)
	goal = models.CharField(max_length=100, blank=True)
	currencyType = models.CharField('currencyType', max_length=100, blank=True)
	endDate = models.CharField('endDate', max_length=100, blank=True)
	numberContributors =models.CharField('numberContributors', max_length=100, blank=True)
	story = models.TextField(blank=True)
	url = models.CharField(max_length=200, blank=True)


	def __str__(self):
		return str(self.campaignTitle) + ' ' + str(self.amountRaised)


class Category(models.Model):
	category = models.CharField(max_length=200, blank=False, null=False)

	def __str__(self):
		return self.category

class Job(models.Model):
	title = models.CharField(max_length=300, blank=False, null=False)
	location = models.CharField(max_length=200, blank=False, null=False)
	category = models.ForeignKey(Category(), on_delete=models.SET_NULL, null=True)

	def __str__(self):
		return self.title

campaigns/forms.py
from . models import Job
from django.forms import ModelForm


class JobSearchForm(ModelForm):

	class Meta:
		model = Job
		fields = '__all__'

campaigns/views.py
from django.shortcuts import render
from rest_framework.views import  APIView
from .models import Campaign, Category, Job
from .serializers import CampaignSerializer
from rest_framework.response import Response
from rest_framework import status
from django.views import generic
from .forms import JobSearchForm
from django.forms import ModelForm


class CampaignView(APIView):

	def get(self, response):
		campaigns = Campaign.objects.all()
		serializer = CampaignSerializer(campaigns, many=True)
		return Response(serializer.data)

	def post(self, response):
		serializer = CampaignSerializer(data=response.data, many=True)
		if serializer.is_valid():
			serializer.save()
			return Response(serializer.data, status=status.HTTP_201_CREATED)
		return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
	
class IndexView(generic.ListView):
	template_name = 'campaigns/index.html'
	model = Category
	form = JobSearchForm()
	contexts = {'form':form}

	def get_queryset(self):
		categories = Category.objects.all() 
		return categories






def results(request):
	if request.method == 'GET':
		results = Job.objects.filter(
			category__category=request.GET['Category'], 
			title__icontains=request.GET['keywords'],
			 location__icontains=request.GET['location'])
	return render(request, 'campaigns/results.html', {'results':results})

campaigns/templates/campaigns/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'campaigns/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'campaigns/font-awesome.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'campaigns/bootstrap.css' %}">
<head>
	


<title>JimohHr | Home </title>


<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="Soft Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
	
<script type="text/javascript">
	$(function(){
		$('#myCarousel').carousel();
	}

		);
</script>

	<script type="application/x-javascript">
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}
	</script>
	<!--my js codes-->
	<a href="{% url 'campaigns:index' %}" class="scroll" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
	<!-- js -->
	<script type="text/javascript" src="{% static 'campaigns/jquery-2.1.4.min.js' %}"></script>

	<script type="text/javascript" src="{% static 'campaigns/bootstrap.js' %}"></script>
</head>

<body>


	<link href="//fonts.googleapis.com/css?family=Work+Sans:200,300,400,500,600,700" rel="stylesheet">
	<link href='//fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700,900,900italic,700italic'
	    rel='stylesheet' type='text/css'>

	   <div class="header" id="home">
		<div class="content white agile-info">
			<nav class="navbar navbar-default" role="navigation">
				<div class="container">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>

					</div>
					<!--/.navbar-header-->
					<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
						<nav class="link-effect-2" id="link-effect-2">
							<ul class="nav navbar-nav">
								<li class="active"><a href="{% url 'campaigns:index' %}" class="effect-3">Home</a></li>
								
							</ul>
						</nav>
					</div>
					<!--/.navbar-collapse-->
					<!--/.navbar-->
				</div>
			</nav>
		</div>

	</div>



	<!--//banner -->


	<!--/search_form -->
	<div id="search_form" class="search_top">
		<h2>Start your job search</h2>
		<form action="{% url 'campaigns:results' %}" method="GET" name='search_form'>
			{% csrf_token %}

			<input type="text" name="keywords" placeholder="Enter Keyword(s)" required="">
			<input class="email" name="location" type="text" placeholder="Location" required="">
			<select id="country12" name="Category" onchange="change_country(this.value)" class="frm-field required">
														<option value="null"> Select Category</option>
														{% for item in category_list %}
														<option name="item" value="{{ item }}">{{ item }}</option>

														{% endfor %}
														
										</select>
			<input type="submit" value="FindJobs">
			<div class="clearfix"></div>
		</form>
	</div>
	<!--//search_form -->

<div class="banner-bottom">
		<div class="container">
			<div class="tittle_head_w3ls">
				<h3 class="tittle">About Us</h3>
			</div>
			<div class="inner_sec_grids_info_w3ls">
				<div class="col-md-6 banner_bottom_left">
					<h4>Employment opportunities for <span>Professionals</span></h4>
					<p>Pellentesque convallis diam consequat magna vulputate malesuada. Cras a ornare elit. Nulla viverra pharetra sem, eget
						pulvinar neque pharetra ac.</p>
					<p>Lorem Ipsum convallis diam consequat magna vulputate malesuada. Cras a ornare elit. Nulla viverra pharetra sem, eget
						pulvinar neque pharetra ac.</p>
					<ul class="some_agile_facts">
						<li><span class="fa fa-briefcase" aria-hidden="true"></span><label>80</label> Corporate Programs</li>
						<li><span class="fa fa-graduation-cap" aria-hidden="true"></span><label>49</label> Training Courses</li>
						<li><span class="fa fa-user" aria-hidden="true"></span><label>88</label> Strategic Partners</li>
						<li><span class="fa fa-line-chart" aria-hidden="true"></span><label>436</label> Companies We Helped</li>
					</ul>
					<div class="clearfix"> </div>
				</div>
				<div class="col-md-6 banner_bottom_right">
					<div class="agileits_w3layouts_banner_bottom_grid">
						<img src="/media/fundrazr/hello.png" alt=" " class="img-responsive" />
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>

		</div>
	</div>
	<!-- //banner-bottom -->

<div class="team_work_agile">
		<h4>Whether we play a large or small role, by working together we achieve our objectives.</h4>
	</div>
	<!-- services -->
	<div class="services" id="services">
		<div class="container">
			<div class="tittle_head_w3ls">
				<h3 class="tittle">Selection Process</h3>
			</div>
			<div class="inner_sec_grids_info_w3ls">
				<div class="col-md-3 services-left">
					<div class="services-left-top">

						<h5>Identify Need & Develop Position Description</h5>

					</div>
					<div class="services-left-top services-left-top1">

						<h5>Recruitment Planning</h5>

					</div>
				</div>
				<div class="col-md-6 services-middle">
					<div class="services-middle-img">
						<img src="media/fundrazr/process.jpg" alt="" />
					</div>
					<div class="services-middle-grids">
						<div class="col-md-6 services-middle-left">
							<div class="services-left-top">

								<h5>AI Assessment</h5>

							</div>
						</div>
						<div class="col-md-6 services-middle-left">
							<div class="services-left-top">

								<h5>Automatic Screening </h5>

							</div>
						</div>
						<div class="clearfix"> </div>
					</div>
				</div>
				<div class="col-md-3 services-left">
					<div class="services-left-top">

						<h5>Online Interview of Successful Candidates</h5>

					</div>
					<div class="services-left-top services-left-top1">

						<h5>Onboarding for Success</h5>

					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<!-- //services -->
	<!-- /mid-services -->
	<div class="mid_services">

		<div class="col-md-6 according_inner_grids">
			<h3 class="agile_heading two">Receiving a Job offer</h3>
			<div class="according_info">
				<div class="panel-group about_panel" id="accordion" role="tablist" aria-multiselectable="true">
					<div class="panel panel-default">
						<div class="panel-heading" role="tab" id="headingOne">
							<h4 class="panel-title asd">
								<a class="pa_italic" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true"
								    aria-controls="collapseOne">
							  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span><i class="glyphicon glyphicon-minus" aria-hidden="true"></i>assumenda est cliche voluptate
							</a>
							</h4>
						</div>
						<div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
							<div class="panel-body panel_text">
								Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
								cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
							</div>
						</div>
					</div>
					<div class="panel panel-default">
						<div class="panel-heading" role="tab" id="headingTwo">
							<h4 class="panel-title asd">
								<a class="pa_italic collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false"
								    aria-controls="collapseTwo">
							  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span><i class="glyphicon glyphicon-minus" aria-hidden="true"></i>Itaque earum rerum
							</a>
							</h4>
						</div>
						<div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
							<div class="panel-body panel_text">
								Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
								cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
							</div>
						</div>
					</div>
					<div class="panel panel-default">
						<div class="panel-heading" role="tab" id="headingThree">
							<h4 class="panel-title asd">
								<a class="pa_italic collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false"
								    aria-controls="collapseThree">
							  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span><i class="glyphicon glyphicon-minus" aria-hidden="true"></i>autem accusamus terry qui
							</a>
							</h4>
						</div>
						<div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
							<div class="panel-body panel_text">
								Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
								cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
							</div>
						</div>
					</div>
					<div class="panel panel-default">
						<div class="panel-heading" role="tab" id="headingThree">
							<h4 class="panel-title asd">
								<a class="pa_italic collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false"
								    aria-controls="collapseThree">
							  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span><i class="glyphicon glyphicon-minus" aria-hidden="true"></i>autem accusamus terry qui
							</a>
							</h4>
						</div>
						<div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
							<div class="panel-body panel_text">
								Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
								cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
							</div>
						</div>
					</div>
				</div>
			</div>

		</div>
		<div class="col-md-6 mid_services_img">
		</div>
		<div class="clearfix"> </div>
	</div>
	<!-- //mid-services -->
	<div class="candidate_cv">
		<div class="tittle_head_w3ls">
			<h3 class="tittle two">Candidate Cv</h3>
		</div>
		<div class="inner_sec_grids_info login-form">
			<form action="#" method="post">
				<div class="col-md-6 form-left">
					<div class="form-inputs email">
						<p>Full name</p>
						<i class="fa fa-user" aria-hidden="true"></i>
						<input type="text" name="Name" placeholder="" required="" />
					</div>
					<div class="form-inputs name">
						<p>Email</p>
						<i class="fa fa-envelope" aria-hidden="true"></i>
						<input type="email" name="Email" placeholder="" required="" />
					</div>
					<div class="form-inputs name">
						<p>Phone</p>
						<i class="fa fa-phone" aria-hidden="true"></i>
						<input type="text" name="Phone" placeholder="" required="" />
					</div>

				</div>
				<div class="col-md-6 form-right">
					<div class="form-inputs name">
						<p>Comment</p>
						<i class="fa fa-comment" aria-hidden="true"></i>
						<textarea name="Message" placeholder="" required=""></textarea>
					</div>
				</div>
				<div class="clearfix"></div>
				<div class="form-inputs">
					<p>Specify your current employment status</p>
					<ul>
						<li>
							<input type="radio" id="a-option" name="selector1">
							<label for="a-option">Employed </label>
							<div class="check"></div>
						</li>
						<li>
							<input type="radio" id="b-option" name="selector1">
							<label for="b-option">Unemployed</label>
							<div class="check"></div>
						</li>
						<li>
							<input type="radio" id="c-option" name="selector1">
							<label for="c-option">Self-Employed</label>
							<div class="check"></div>
						</li>
						<li>
							<input type="radio" id="d-option" name="selector1">
							<label for="d-option">Student</label>
							<div class="check"></div>
						</li>
					</ul>
					<div class="clearfix"></div>
				</div>
				<div class="form-inputs upload">
					<p>Upload your resume</p>
					<input type="file" id="fileselect" name="fileselect[]" multiple="multiple" />
					<div id="filedrag">Upload</div>
				</div>
				<input type="submit" value="Submit Cv">
			</form>

		</div>
	</div>
	<!-- //testimonials -->




	
</body>
















</body>

















	

campaigns/templates/campaigns/results.html
{% load static %}
	<!--//tags -->
<link rel="stylesheet" type="text/css" href="{% static 'campaigns/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'campaigns/font-awesome.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'campaigns/bootstrap.css' %}">

<head>
	<title>JimohHr | Home </title>
	<!--/tags -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="Soft Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
	<script type="application/x-javascript">
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}
	</script>

</head>

<body>
	<!-- header -->
	<div class="header" id="home">
		<div class="content white">
			<nav class="navbar navbar-default" role="navigation">
				<div class="container">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
						
					</div>
					<!--/.navbar-header-->

					<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
						<nav class="link-effect-2" id="link-effect-2">
							<ul class="nav navbar-nav">
								<li class="active"><a href="{% url 'campaigns:index' %}" class="effect-3">Home</a></li>
								
							</ul>
						</nav>
					</div>
					<!--/.navbar-collapse-->
					<!--/.navbar-->
				</div>
			</nav>
		</div>
	</div>
	<!-- banner -->
	<!--//banner -->
	<!--/w3_short-->
	
	<!--//w3_short-->
	<!-- /inner_content -->
	<div class="inner_content_info">


		<div class="container">
			{% if results %}
			<div class="tittle_head">
				<h3 class="tittle">Available Jobs </h3>
			</div>
			<div class="inner_sec_grids_info">
				<div class="col-md-8 job_info_left">
					<div class="but_list">
						<div class="bs-example bs-example-tabs" role="tabpanel" data-example-id="togglable-tabs">
							<ul id="myTab" class="nav nav-tabs" role="tablist">
								<li role="presentation" class="active"><a href="#home" id="home-tab" role="tab" data-toggle="tab" aria-controls="home" aria-expanded="true">Search Results</a></li>
								<li role="presentation" style="visibility: hidden;"><a href="#profile" role="tab" id="profile-tab" data-toggle="tab" aria-controls="profile">Show Descriptions</a></li>
							</ul>
							<div id="myTabContent" class="tab-content">
								<div role="tabpanel" class="tab-pane fade in active" id="home" aria-labelledby="home-tab">
									
									{% for result in results %}

									<div class="tab_grid">
										<div class="col-sm-3 loc_1">
											<a href="location_single.html"><img src="/media/fundrazr/loc1.jpg" alt=""></a>
										</div>
										<div class="col-sm-9">
											<div class="location_box1">
												<h6><a href=".">{{ result.title }}  </a><span class="m_1" style="visibility: hidden;">Posted 5 hours ago</span></h6>
												<p><span class="m_2">Location : {{ result.location }} </span> <br>On the other hand, we denounce with righteous indignation and dislike men
													who are so beguiled and demoralized by the charms of pleasure</p>
												<ul class="links_bottom" style="visibility: hidden;">
													<li><a href="location_single.html"><i class="fa fa-envelope-o icon_1"> </i><span class="icon_text"> Email this Job</span></a></li>
													<li><a href="location_single.html"><i class="fa fa-eye icon_1"> </i> <span class="icon_text">View full Job Description</span></a></li>
													<li class="last"><a href="location_single.html"><span class="icon_text">More <i class="fa fa-caret-right icon_1"> </i></span></a></li>
												</ul>
											</div>
										</div>
										<div class="clearfix"> </div>
									</div>	
									{% endfor %}
								</div>
							</div>
							
						</div>
					</div>
				</div>
			</div>	
			

		{% else %}
<div class="container">
			<div class="tittle_head">
				<h3 class="tittle">Available Jobs </h3>
			</div>
		</div>
		
{% endif %}
			
			<div class="col-md-4 job_info_right">

				<div class="widget_search">
					<h5 class="widget-title">Search</h5>
					<div class="widget-content">
						<span>I'm looking for a ...</span>
						<select class="form-control jb_1">
					<option value="0">Job</option>
					<option value="">Category</option>
					<option value="">Category</option>
					<option value="">Category</option>
					<option value="">Category</option>
				</select>
						<span>in</span>
						<input type="text" class="form-control jb_2" placeholder="Location">
						<input type="text" class="form-control jb_2" placeholder="Industry / Role">
						<input type="submit" value="Search">
					</div>
				</div>
				<div class="col_3 permit">
					<h3>Jobs by Category</h3>
					<ul class="list_2">
						<li><a href="#">Railway Recruitment</a></li>
						<li><a href="#">Air Force Jobs</a></li>
						<li><a href="#">Police Jobs</a></li>
						<li><a href="#">Intelligence Bureau Jobs</a></li>
						<li><a href="#">Army Jobs</a></li>
						<li><a href="#">Navy Jobs</a></li>
						<li><a href="#">BSNL Jobs</a></li>
						<li><a href="#">Software Jobs</a></li>
						<li><a href="#">Research Jobs</a></li>
					</ul>
				</div>
				<div class="col_3 experience">
					<h3>Work Experiance</h3>
					<table class="table">
						<tbody>
							<tr class="unread checked">
								<td class="hidden-xs">
									<input type="checkbox" class="checkbox">
								</td>
								<td class="hidden-xs">
									Junior
								</td>
								<td>
									(56)
								</td>
							</tr>
							<tr class="unread checked">
								<td class="hidden-xs">
									<input type="checkbox" class="checkbox">
								</td>
								<td class="hidden-xs">
									Senior
								</td>
								<td>
									(56)
								</td>
							</tr>
							<tr class="unread checked">
								<td class="hidden-xs">
									<input type="checkbox" class="checkbox">
								</td>
								<td class="hidden-xs">
									Middle
								</td>
								<td>
									(56)
								</td>
							</tr>
							<tr class="unread checked">
								<td class="hidden-xs">
									<input type="checkbox" class="checkbox">
								</td>
								<td class="hidden-xs">
									Junior
								</td>
								<td>
									(56)
								</td>
							</tr>
							<tr class="unread checked">
								<td class="hidden-xs">
									<input type="checkbox" class="checkbox">
								</td>
								<td class="hidden-xs">
									Junior
								</td>
								<td>
									(56)
								</td>
							</tr>
							<tr class="unread checked">
								<td class="hidden-xs">
									<input type="checkbox" class="checkbox">
								</td>
								<td class="hidden-xs">
									Junior
								</td>
								<td>
									(56)
								</td>
							</tr>
							<tr class="unread checked">
								<td class="hidden-xs">
									<input type="checkbox" class="checkbox">
								</td>
								<td class="hidden-xs">
									Junior
								</td>
								<td>
									(56)
								</td>
							</tr>
							<tr class="unread checked">
								<td class="hidden-xs">
									<input type="checkbox" class="checkbox">
								</td>
								<td class="hidden-xs">
									Junior
								</td>
								<td>
									(56)
								</td>
							</tr>
							<tr class="unread checked">
								<td class="hidden-xs">
									<input type="checkbox" class="checkbox">
								</td>
								<td class="hidden-xs">
									Junior
								</td>
								<td>
									(56)
								</td>
							</tr>
						</tbody>
					</table>
				</div>
				<div class="col_3 permit">
					<h3>Work Permit</h3>
					<table class="table">
						<tbody>
							<tr class="unread checked">
								<td class="hidden-xs">
									<input type="checkbox" class="checkbox">
								</td>
								<td class="hidden-xs">
									Full time
								</td>
							</tr>
							<tr class="unread checked">
								<td class="hidden-xs">
									<input type="checkbox" class="checkbox">
								</td>
								<td class="hidden-xs">
									Part time
								</td>
							</tr>
						</tbody>
					</table>
				</div>

			</div>
			<div class="clearfix"></div>
		</div>
	</div>
	<!-- //inner_content -->
	<!-- footer -->
	<div class="footer_top">
		<div class="container">
			<div class="col-md-4 footer_grid">
				<h3>About Us</h3>
				<p>Nam libero tempore cum vulputate id est id, pretium semper enim. Morbi viverra congue nisi vel pulvinar posuere sapien
					eros.
				</p>
			</div>
			<div class="col-md-4 footer_grid">
				<h3>Latest News</h3>
				<ul class="footer_grid_list">
					<li><i class="fa fa-long-arrow-right" aria-hidden="true"></i>
						<a href="single.html" >Lorem ipsum neque vulputate </a>
					</li>
					<li><i class="fa fa-long-arrow-right" aria-hidden="true"></i>
						<a href="single.html" >Dolor amet sed quam vitae</a>
					</li>
					<li><i class="fa fa-long-arrow-right" aria-hidden="true"></i>
						<a href="single.html" >Lorem ipsum neque, vulputate </a>
					</li>
					<li><i class="fa fa-long-arrow-right" aria-hidden="true"></i>
						<a href="single.html" >Dolor amet sed quam vitae</a>
					</li>
					<li><i class="fa fa-long-arrow-right" aria-hidden="true"></i>
						<a href="single.html" >Lorem ipsum neque, vulputate </a>
					</li>
				</ul>
			</div>
			<div class="col-md-4 footer_grid">
				<h3>Contact Info</h3>
				<ul class="address">
					<li><i class="fa fa-map-marker" aria-hidden="true"></i>8088 USA, Honey block, <span>New York City.</span></li>
					<li><i class="fa fa-envelope" aria-hidden="true"></i><a href="mailto:info@example.com">info@example.com</a></li>
					<li><i class="fa fa-phone" aria-hidden="true"></i>+09187 8088 9436</li>
				</ul>
			</div>
			<div class="clearfix"> </div>
			<div class="footer_grids">
				<div class="col-md-4 footer_grid_left">
					<h3>Sign up for our Newsletter</h3>
				</div>
				<div class="col-md-8 footer_grid_right">

					<form action="#" method="post">
						<input type="email" name="Email" placeholder="Enter Email Address..." required="">
						<input type="submit" value="Submit">
					</form>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<div class="footer">
		<div class="container">
			<div class="footer_bottom">
				<div class="col-md-9 footer_bottom_grid">
					<div class="footer_bottom1">
						<a href="index.html">
							<h2><span class="fa fa-signal" aria-hidden="true"></span> Soft <label>Hr Agency</label></h2>
						</a>
						<p>© 2017 Soft. All rights reserved.</p>
					</div>
				</div>
				<div class="col-md-3 footer_bottom_grid">
					<h6>Follow Us</h6>
					<div class="social">
						<ul>
							<li><a href="#"><i class="fa fa-facebook"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter"></i></a></li>
							<li><a href="#"><i class="fa fa-rss"></i></a></li>
						</ul>
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>

		</div>
	</div>
	<!-- //footer -->

	<a href="#home" class="scroll" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
	<!-- js -->
	<script type="text/javascript" src="js/jquery-2.1.4.min.js"></script>
	<script type="text/javascript" src="js/bootstrap.js"></script>
</body>

</html>